version: '3.1'

networks:
  my_network: 
    driver: bridge

services:

  database:
    image: mysql
    container_name: my_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - my_database:/var/lib/mysql
    networks:
      - my_network

  my_aplication:
    build:
      dockerfile: PHP.Dockerfile
      context: .
    image: my_php_image
    container_name: my_aplication
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./php/:/var/www/html/
      - ./config/:/usr/local/etc/php
    depends_on:
      - database
    networks:
      - my_network

volumes:
  my_database: